apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atlassian-jira-persistent-storage
  labels:
    app: atlassian-jira-persistent-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
