apiVersion: v1
kind: Service
metadata:
  name: atlassian-jira
  labels:
    name: atlassian-jira
spec:
  type: NodePort
  selector:
    name: atlassian-jira
  ports:
    - name: http
      port: 8080
      targetPort: 8080
